#!/usr/bin/env bash
# shellcheck disable=SC2009

# Find the PID(s) of the 4-to_infinity_and_beyond script
pid=$(ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

# If PID exists, kill it
if [ -n "$pid" ]; then
  kill "$pid"
fi

