#!/usr/bin/env bash
#while loop and if , elif and else implementation
i=0
while [[ $i -le 10 ]];
do
echo "Best School"
if [[ $i -eq 4 ]]; then
echo "bad luck"
elif [[ $i -eq 8 ]]; then
echo "good luck"
else
echo "Best School"
fi

i=$((i+1))
done
