#!/usr/bin/env bash
#implementation of file manipulation using if and else statements
 if [ -e "$school" ]; then
   echo " school file exists "
   if [ ! -s "$school" ]; then
   echo "school file is empty"
   fi
   if [ -s "$school" ]; then
   echo "school file is not empty"
   fi
   if [ -f "$school" ]; then
   echo "school is a regular file"
   fi
#this if statement is for when it exists but is not a regular file
   if [ ! -f "$school"]; then
    echo " "
   fi
  else
    echo " school file does not exist "
  fi
